### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException in Candidate.java

### ISSUE THREAD

**Issue by dtkaczyk** [CrossRef/search-based-reference-matcher#3]
Matching strings:

`(1) Sánchez, M.; Cuevas, C.; Rincón, M. E. 2010.`
`[1] M. Sánchez, C. Cuevas, M.E. Rincón, (2010).`

results in:

`Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 45
	at java.lang.String.substring(String.java:1963)
	at org.crossref.refmatching.Candidate.getStringValidationSimilarity(Candidate.java:134)
	at org.crossref.refmatching.Candidate.getValidationSimilarity(Candidate.java:44)
	at org.crossref.refmatching.CandidateValidator.lambda$chooseCandidate$0(CandidateValidator.java:25)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.crossref.refmatching.CandidateValidator.chooseCandidate(CandidateValidator.java:26)
	at org.crossref.refmatching.SBMVMatcher.match(SBMVMatcher.java:113)
	at org.crossref.refmatching.SBMVMatcher.match(SBMVMatcher.java:72)
	at org.crossref.refmatching.ReferenceMatcher.main(ReferenceMatcher.java:100)`

**Comment by dtkaczyk** [comment]
Fixed.
